### ISSUE TITLE
Wrong value with EnhancedAvgSpeedScaled()

### ISSUE THREAD

**Issue by Oupsman** [muktihari/fit#397]
Hi, 

After my first issue, I worked a little more on my code and I encounter an issue with some fit files : the EnhancedAvgSpeedScaled() function gives me 65.535 as the avg speed during the session (AvgSpeedScaled() gives me NaN).

```
(venv) ➜  prototypes git:(main) ✗ /usr/local/go/bin/go run read_fit.go
File Type: activity
EnhancedAvgSpeedScaled: 65.535000
AvgSpeedScaled: NaN
EnhancedAvgSpeed: 65535
AvgSpeed: 65535
```

The code :

```
package main

import (
	"fmt"
	"github.com/muktihari/fit/decoder"
	"github.com/muktihari/fit/profile/filedef"
	"os"
)

func main() {
	// filePath := "FIT/Karoo-Morning_Ride-Sep-06-2022-061544.fit"
	filePath := "2022-08-30-18-12-37.fit"
	f, err := os.Open(filePath)
	if err != nil {
		panic(err)
	}
	defer f.Close()

	dec := decoder.New(f)
	// Read the fit file

	for dec.Next() {
		fit, err := dec.Decode()
		if err != nil {
			panic(err)
		}
		activity := filedef.NewActivity(fit.Messages...)

		fmt.Printf("File Type: %s\n", activity.FileId.Type)
		fmt.Printf("EnhancedAvgSpeedScaled: %f\n", activity.Sessions[0].EnhancedAvgSpeedScaled())
		fmt.Printf("AvgSpeedScaled: %f\n", activity.Sessions[0].AvgSpeedScaled())
		fmt.Printf("EnhancedAvgSpeed: %d\n", activity.Sessions[0].EnhancedAvgSpeed)
		fmt.Printf("AvgSpeed: %d\n", activity.Sessions[0].AvgSpeed)
	
	}

}
```

I analyzed the fit file with a little program in Python and the results are fine : 

```
➜  prototypes git:(main) ✗ python test.py | grep speed
enhanced_avg_speed 6.288
```

```
import fitparse


fitfile = fitparse.FitFile("2022-08-30-18-12-37.fit")    
    
for record in fitfile.get_messages('session'):
  record_list = {}
  for record_data in record:
    if record_data.value is not None:
      print(record_data.name, record_data.value)
```

I can send you the FIT file if you need it.

**Comment by muktihari** [comment]
AvgSpeed is an uint16 and its invalid value is math.MaxUint16 (65535). 
EnhancedAvgSpeed is an uint32 and its invalid value is math.MaxUint32 (4294967295). 

So having 65535 for EnhancedAvgSpeed is still a valid value. I assume the file is encoded incorrectly.

Both AvgSpeed and EnhancedAvgSpeed have scale 1000 and  offset 0. 
ScaledValue formula: **_IntegerValue / scale - offset_**
So the scaled value of 65535 will be **_65.535_**
Ref: **Profile.xlsx** spec in https://developer.garmin.com/fit/download

The value returned by fitparse "6.288" is questionable actually. 

fitparse is another unnofficial FIT parser library and I don't know how they handle FIT files. If you want to compare the validity and since you use python  I recommend you to use official fit sdk for python: https://github.com/garmin/fit-python-sdk.

**Comment by Oupsman** [comment]
The value returned by fitparse is the same than Garmin Connect

Besides, the official Python SDK gives me the same value as fitparse

**Comment by muktihari** [comment]
I see, let me see the file so I can debug it, either share a gdrive link or sent it to muktihaz+fit@gmail.com

**Comment by muktihari** [comment]
Hi @Oupsman, I think I know the problem, the invalid value comes from component expansion. Currently, decoder does not check the validity of the value before expanding the field's components. When we convert mesg into mesgdef.Session, we do a simple for-loop and the correct value got overwritten.

```go
for _, mesg := range fit.Messages {
	if mesg.Num != mesgnum.Session {
		continue
	}
	for i, field := range mesg.Fields {
		if field.Num == fieldnum.SessionEnhancedAvgSpeed {
			fmt.Printf("[i:%3d] EnhancedAvgSpeed: %5d [Expanded: %t]\n",
				i, field.Value.Uint32(), field.IsExpandedField)
		}
	}
}
```
Output:
```sh
[i: 25] EnhancedAvgSpeed:  6288 [Expanded: false]
[i:116] EnhancedAvgSpeed: 65535 [Expanded: true]
```

I haven't found documentation regarding this, when I look that the official C# and Java SDK they doesn't seem to handle this as well (CMIIW), but when I look at the Official Python SDK, it does skip invalid value. So I think the appropriate way is to not expand the field's components if it's an invalid value. 

However, the fix works with caveats, if in Session contains both valid AvgSpeed and EnhancedAvgSpeed, the decoder will produce two EnhancedAvgSpeed fields. But for all the FIT files that I have, the best practice is to use only one field at a time (FIT produces from Garmin devices uses EnhancedAvgSpeed, and make AvgSpeed invalid).

I will release the v0.21.5 to address this issue.

**Comment by muktihari** [comment]
**v0.21.5** is out now, you can try it, run this following command:
```sh
go get -u github.com/muktihari/fit@v0.21.5
```

Let me know if this solve this issue.

**Comment by Oupsman** [comment]
It works, thanks a lot.

**Comment by muktihari** [comment]
Great, I will close the issue now. Thank you for spotting the bug, appreciate it.
